// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nexhse-projects/Current.tsx": () => import("../components/mockups/nexhse-projects/Current.tsx"),
  "./components/mockups/nexhse-projects/OrganicBlend.tsx": () => import("../components/mockups/nexhse-projects/OrganicBlend.tsx"),
  "./components/mockups/nexhse-contact/Current.tsx": () => import("../components/mockups/nexhse-contact/Current.tsx")
};
